### PR TITLE
Upgrade to Pants 2.8.0.dev4.

### PR DESCRIPTION
**Pull request by benjyw**
It's not ideal to use a dev version in an example repo, but
this allows us to streamline this repo by removing the
global venv and instead demonstrate running manage.py commands
via `./pants run` - even runserver, with pants triggering
restarts!

### CODE REVIEW

**Comment by benjyw** [comment]
cc @g-cassie

**Comment by benjyw** [comment]
> The other small win I had in 2.8 was to make a pex_binary for django-admin in the root BUILD file like this:

Nice. May merge that separately though.

**Review by Eric-Arellano — APPROVED** [review]
Should this also use an alias so it's less verbose? I imagine almost every org would want to set that up.

**Comment by benjyw** [comment]
> Should this also use an alias so it's less verbose? I imagine almost every org would want to set that up.

Sorry, what is the "this" here?

**Comment by Eric-Arellano** [comment]
This PR, an alias for `./pants run path/to:manage_py_bin --` so that all the user rules is `./pants manage-py --help`

**Comment by benjyw** [comment]
There will be multiple manage.py in a repo, so that kind of alias doesn't really make sense.

**Pull request merged**
